#testing
name: 'Terraform Automation'

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  Build:
    name: 'build'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        
  Deploy-to-Terraform-dev:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: 'Deploy to Terraform-dev'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        
    steps:
      - name: demo
        run: echo "hello world"
        
    
  Deploy-to-Terraform-qa:
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    name: 'Deploy to Terraform-qa'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash 
        
    steps:
      - name: demo
        run: echo "hello world"   


  Deploy-to-Terraform-prod:
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    name: 'Deploy to Terraform-prod'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
     
    steps:
      - name: demo
        run: echo "hello world"
