#testing
name: 'Terraform Automation'

on:
  push:
    branches:
      - main
      - dev
      - qa
      - prod

jobs:
  Build:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: 'Build'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: if qa, terraform init, validate, plan, apply
        if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
        run: |
          terraform init
          terraform validate -no-color
          terraform plan -no-color
          terraform apply -auto-approve  
          #terraform destroy
          
  Deploy-to-Terraform-dev:
    needs: Build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: 'Deploy to Terraform-dev'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
        
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: if qa, terraform init, validate, plan, apply
        if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
        run: |
          #cd ppb
          terraform init
          terraform validate -no-color
          terraform plan -no-color
          terraform apply -auto-approve
        
    
  Deploy-to-Terraform-qa:
    needs: Build
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    name: 'Deploy to Terraform-qa'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash 
        
    steps:
      - name: demo
        run: echo "hello world"   


  Deploy-to-Terraform-prod:
    needs: Build
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    name: 'Deploy to Terraform-prod'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash
     
    steps:
      - name: demo
        run: echo "hello world"
        
        
